# POD - API configuration
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Normal service name
  name: ms-customer-massive-client-loader
spec:
  # Number of replicas
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ms-customer-massive-client-loader
  template:
    metadata:
      labels:
        # Normal service name and tier (same selectors as the service configuration)
        app: ms-customer-massive-client-loader
        tier: backend
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      # Normal service name
      - name: ms-customer-massive-client-loader
        # Change to your project image (from registry)
        image: {GCLOUD_REGISTRY_HOST}/{GCP_PROJECT_ID}/{CI_PROJECT_NAME}:{IMAGE_TAG}
        # Always download the image from registry (dev utility)
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        resources:
          # You must specify requests for CPU to autoscale
          # based on CPU utilization
          requests:
            cpu: "400m"
        env:
          - name: PORT
            valueFrom:
                configMapKeyRef:
                  name:  ms-customer-massive-client-loader-env
                  key: PORT

          - name: DS_HOST
            valueFrom:
                configMapKeyRef:
                  name:  ms-customer-massive-client-loader-env
                  key: DS_HOST

          - name: DS_DB
            valueFrom:
                configMapKeyRef:
                  name:  ms-customer-massive-client-loader-env
                  key: DS_DB

          - name: DS_PORT
            valueFrom:
                configMapKeyRef:
                  name:  ms-customer-massive-client-loader-env
                  key: DS_PORT

          - name: SYSTEM_DATASOURCE_USER
            valueFrom:
              secretKeyRef:
                name: farenasl-cloudsql-db-credentials
                key: username
      
          - name: SYSTEM_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: farenasl-cloudsql-db-credentials
                key: password
        volumeMounts:        
          - name: secret-credential-massive-client-loader-jwt
            mountPath: /api/v1/namespaces/farenasl/secrets/
            readOnly: true
      # [END volumes]
      # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
      # project, the region of your Cloud SQL instance and the name
      # of your Cloud SQL instance. The format is
      # $PROJECT:$REGION:$INSTANCE
      # [START proxy_container]
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances={INSTANCE_CONNECTION_NAME}=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: farenasl-cloudsql-instance-credentials
            mountPath: /secrets/cloudsql/
            readOnly: true
      # [END proxy_container]
      # [START volumes]
      volumes:
        - name: farenasl-cloudsql-instance-credentials
          secret:
            secretName: farenasl-cloudsql-instance-credentials 
        - name: secret-credential-massive-client-loader-jwt
          secret:
            secretName: secret-credential-massive-client-loader-jwt       
      # [END volumes]
  